# shopify.app.toml
name = "Anorha"
client_id = "YOUR_SHOPIFY_CLIENT_ID"
handle = "sssync-backend"
application_url = "https://www.sssync.app/"
scopes = "read_analytics,write_inventory,read_inventory,write_inventory_transfers,read_inventory_transfers,write_order_edits,read_order_edits,read_orders,write_orders,read_products,write_products,write_reports,read_reports"

[webhooks]
api_version = "2025-04"

[[webhooks.subscriptions]]
topics = ["products/create", "products/update", "products/delete"]
uri = "pubsub://anorha:shopify-webhooks"

[[webhooks.subscriptions]]
topics = ["inventory_levels/update"]
uri = "pubsub://anorha:shopify-webhooks"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "pubsub://anorha:shopify-webhooks"
