# shopify.app.toml
name = "Anorha"
client_id = "ae3001d773b024a1b08167593bb833a9"
handle = "anorha"
application_url = "https://app.anorha.app/"
embedded = false

[access_scopes]
scopes = "read_analytics,write_inventory,read_inventory,write_inventory_transfers,read_inventory_transfers,write_order_edits,read_order_edits,read_orders,write_orders,read_products,write_products,write_reports,read_reports"

[auth]
redirect_urls = [
    "https://api.sssync.app/api/auth/shopify/callback",
    "https://api.sssync.app/api/auth/shopify/store-picker-callback",
    "https://anorhaapp//auth-callback"
]

[webhooks]
api_version = "2025-04"

[[webhooks.subscriptions]]
topics = ["products/create", "products/update", "products/delete"]
uri = "https://api.sssync.app/api/webhooks/shopify"

[[webhooks.subscriptions]]
topics = ["inventory_levels/update"]
uri = "https://api.sssync.app/api/webhooks/shopify"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "https://api.sssync.app/api/webhooks/shopify"
